### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Only-Moon** [Yash094/Discord-Dashboard-Bot#3]
Its a suggestion that discord-buttons dont support discord.js v13 , so maybe work on it to make it v13 compatible by changing v13 things to v13.

p.s. If you need a helper, I am up for it.

**Comment by Yash094** [comment]
Hello Mohit,

We always appreciate your contributions to the bot,
if you can please make a pull request with the v13 buttons.
[ Sorry for the late reply ] 

Thank you,
Yash
